#colors
red=$(tput setaf 1)
green=$(tput setaf 2)
cyan=$(tput setaf 6)
pink=$(tput bold ; tput setaf 5)
reset=$(tput sgr0)

gitStatus() { git diff --quiet 2> /dev/null || echo ' *' ; }
gitBranch() { git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/ (\1$(gitStatus))/" ; }

PS1="[\[$green\]\T\[$reset\]] \[$red\]\u\[$reset\] [\[$cyan\]\w\[$reset\]]\[$pink\]\$(gitBranch)\[$reset\] \$ "
PS2=" > "

# the path is initially set to "/bin:/sbin:/usr/bin:/usr/sbin"
export PATH=/Applications/Postgres.app/Contents/MacOS/bin:/usr/local/bin:$PATH:./bin

# include node bin executables
export PATH=$PATH:/usr/local/share/npm/bin

# aliases
alias l="ls -l"
alias ll="ls -al"
alias reload="source ~/.bash_profile"
alias dropbox="cd ~/Dropbox"
alias code="cd ~/Dropbox/code"
alias s="subl ."
alias cleardns="dscacheutil -flushcache"
alias unic="CACHE=true bundle exec unicorn_rails -c config/unicorn_development.rb"
alias uni="bundle exec unicorn_rails -c config/unicorn_development.rb"
alias rdb="rake db:migrate db:test:prepare"
alias be="bundle exec"
alias t="ruby -I test"
alias z="zeus"
alias blog="cd ~/Dropbox/code/blog"
alias watch="cd ~/Dropbox/code/blog && bin/rake watch"
alias es="elasticsearch -f -D es.config=/usr/local/opt/elasticsearch/config/elasticsearch.yml"

source ~/.git-completion.sh

# Shut off control flow in terminal so we can use vim shortcut <c-s>
stty -ixon -ixoff

eval "$(rbenv init -)"

# Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export RUBY_GC_MALLOC_LIMIT=60000000
export RUBY_FREE_MIN=200000

