#colors
red=$(tput setaf 1)
green=$(tput setaf 2)
cyan=$(tput setaf 6)
pink=$(tput bold ; tput setaf 5)
reset=$(tput sgr0)

gitStatus() { git diff --quiet 2> /dev/null || echo ' *' ; }
gitBranch() { git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/ (\1$(gitStatus))/" ; }

PS1="[\[$green\]\T\[$reset\]] \[$red\]\u\[$reset\] [\[$cyan\]\w\[$reset\]]\[$pink\]\$(gitBranch)\[$reset\] \$ "
PS2=" > "

# the path is initially set to "/bin:/sbin:/usr/bin:/usr/sbin"
export PATH=/usr/local/bin:$PATH:./bin

# include node bin executables
export PATH=$PATH:/usr/local/share/npm/bin

# aliases
alias v="vim"
alias l="ls -l"
alias ll="ls -al"
alias gp="git push"
alias gpull="git pull"
alias gb="git branch"
alias ga="git add -p"
alias gs="git status"
alias gaa="git add --all"
alias gc="git commit"
alias gl="git co -"
alias gm="git merge"
alias gcom="git co master"
alias gco="git checkout -b"
alias gph="git push heroku"
alias reload="source ~/.bash_profile"
alias dropbox="cd ~/Dropbox"
alias godir="cd ~/Dropbox/code/go/src/github.com"
alias code="cd ~/Dropbox/code"
alias cleardns="dscacheutil -flushcache"
alias unic="CACHE=true bundle exec unicorn_rails -c config/unicorn_development.rb"
alias uni="bundle exec unicorn_rails -c config/unicorn_development.rb"
alias be="bundle exec"
alias rdb="be rake db:migrate db:test:prepare"
alias t="ruby -I test"
alias delete_logs="code && find . -type f -iwholename '*log/test.log'  -o -iwholename '*log/production.log' -o -iwholename '*log/development.log' | xargs rm -f"
alias slave="ssh -L 3306:localhost:3306 dbslave"
alias fs="foreman start"
alias dock='eval "$(docker-machine env default)"'

source ~/.git-completion.sh

# Shut off control flow in terminal so we can use vim shortcut <c-s>
stty -ixon -ixoff

eval "$(rbenv init -)"

# Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export GOPATH=~/Dropbox/code/go
export PATH=$PATH:$GOPATH/bin

export JAVA_HOME=/Library/Java/Home
export AWS_CREDENTIAL_FILE=~/Dropbox/code/aws/aws-credential.template

tab() # new tab from current dir
{
  osascript -e "
  tell application \"iTerm\"
    tell the first terminal
      launch session \"Default Session\"
      tell the last session
        write text \"cd $(pwd)\"
      end tell
    end tell
  end tell"
}
