#colors
red=$(tput setaf 1)
green=$(tput setaf 2)
cyan=$(tput setaf 6)
pink=$(tput bold ; tput setaf 5)
reset=$(tput sgr0)

gitStatus() { git diff --quiet 2> /dev/null || echo ' *' ; }
gitBranch() { git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/ (\1$(gitStatus))/" ; }

PS1="[\[$green\]\T\[$reset\]] \[$red\]\u\[$reset\] [\[$cyan\]\w\[$reset\]]\[$pink\]\$(gitBranch)\[$reset\] \$ "
PS2=" > "

# the path is initially set to "/bin:/sbin:/usr/bin:/usr/sbin"
export PATH=/Applications/Postgres.app/Contents/MacOS/bin:/usr/local/bin:$PATH:./bin

# include node bin executables
export PATH=$PATH:/usr/local/share/npm/bin

# aliases
alias v="vim"
alias l="ls -l"
alias ll="ls -al"
alias gp="git push"
alias gpull="git pull"
alias gb="git branch"
alias ga="git add -p"
alias gs="git status"
alias gaa="git add --all"
alias gc="git commit"
alias gl="git co -"
alias gm="git merge"
alias gcodev="git co develop"
alias gcom="git co master"
alias gco="git checkout -b"
alias gph="git push heroku"
alias reload="source ~/.bash_profile"
alias dropbox="cd ~/Dropbox"
alias code="cd ~/Dropbox/code"
alias s="subl ."
alias cleardns="dscacheutil -flushcache"
alias unic="CACHE=true bundle exec unicorn_rails -c config/unicorn_development.rb"
alias uni="bundle exec unicorn_rails -c config/unicorn_development.rb"
alias be="bundle exec"
alias rdb="be rake db:migrate db:test:prepare"
alias t="ruby -I test"
alias z="zeus"
alias blog="cd ~/Dropbox/code/blog"
alias watch="cd ~/Dropbox/code/blog && bin/rake watch"
alias es="elasticsearch -f -D es.config=/usr/local/opt/elasticsearch/config/elasticsearch.yml"
alias delete_logs="code && find . -type f -iwholename '*log/test.log'  -o -iwholename '*log/production.log' -o -iwholename '*log/development.log' | xargs rm -f"

source ~/.git-completion.sh

# Shut off control flow in terminal so we can use vim shortcut <c-s>
stty -ixon -ixoff

eval "$(rbenv init -)"

# Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export GOPATH=~/Dropbox/code/go
export PATH=$PATH:$GOPATH/bin

export JAVA_HOME=/Library/Java/Home
export AWS_IAM_HOME=~/Dropbox/code/aws/iam
export AWS_AUTO_SCALING_HOME=~/Dropbox/code/aws/autoscaling
export EC2_HOME=~/Dropbox/code/aws/ec2
export AWS_CREDENTIAL_FILE=~/Dropbox/code/aws/aws-credential.template
export PATH="$PATH:$AWS_IAM_HOME/bin"
export PATH="$PATH:$AWS_AUTO_SCALING_HOME/bin"
export PATH="$PATH:$EC2_HOME/bin"

tab() # new tab from current dir
{
  osascript -e "
  tell application \"iTerm\"
    tell the first terminal
      launch session \"Default Session\"
      tell the last session
        write text \"cd $(pwd)\"
      end tell
    end tell
  end tell"
}
